1.1 - Write a function to compute 5/0 and use try/except to catch the exceptions

In [8]:
print("-" * 60 )

# try block to catch the zero divide error 
try :
    a = 5/0
except ZeroDivisionError :
    print ("A zero divide error has occurred. Please check !!")
else :
    print(a)

print("-" * 60 )

------------------------------------------------------------
A zero divide error has occurred. Please check !!
------------------------------------------------------------


1.2 - Implement a Python program to generate all sentences 
where 
subject is in ["Americans","Indians"]
and verb is in ["Play", "watch"] 
and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

Output should come as below:
Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket

In [12]:
# Implementation of addition of Matrices

subjects = ["Americans","Indians"] 
verbs=["play","watch"]
objects=["Baseball","Cricket"]

print("-" * 60 )

for i in range(len(subjects)) :
    for j in range(len(verbs)) :
        for k in range(len(objects)) :
            l = subjects[i] + " " + verbs[j] + " " + objects[k]
            print(l)
            
print("-" * 60 )

------------------------------------------------------------
Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket
------------------------------------------------------------


2.1 - Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde

In [37]:
import numpy as np 
   
def gen_vander_matrix(inputVector, n, increasing=False):
    
    if not increasing:
        output_matx = np.array([x**(n-1-i) for x in inputVector for i in range(n)]).reshape(inputVector.size,n)
    elif increasing:
        output_matx = np.array([x**i for x in inputVector for i in range(n)]).reshape(inputVector.size,n)    
    return output_matx

print("-" * 60 )

inputvector = np.array([1,2,3,4,5,6])
numberOfColumnsInOutputMatx = 3
vand_matx_inc_order = gen_vander_matrix(inputvector,numberOfColumnsInOutputMatx,True)
vand_matx_dec_order = gen_vander_matrix(inputvector,numberOfColumnsInOutputMatx,False)

print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",numberOfColumnsInOutputMatx,"\n")
print("-" * 60 )
print("Vander matrix of the input array in increasing order of powers:\n\n",vand_matx_inc_order,"\n")
print("-" * 60 )
print("Vander matrix of the input array in decreasing order of powers:\n\n",vand_matx_dec_order,"\n")
print("-" * 60 )

------------------------------------------------------------
The input array is: [1 2 3 4 5 6] 

Number of columns in output matrix should be: 3 

------------------------------------------------------------
Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]
 [ 1  6 36]] 

------------------------------------------------------------
Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]
 [36  6  1]] 

------------------------------------------------------------
